spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.main.allow-bean-definition-overriding=true

bot.token=${BOT_TOKEN}
bot.admin.id=${BOT_ADMIN_ID}
bot.group.id=-${BOT_GROUP_ID}

logging.level.root=info
//level.com.example.bot=debug
logging.file.name=logs/application.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7